django/website/package/urls.py
from django.conf.urls import patterns, url
from django.views.generic.dates import ArchiveIndexView

from package.models import Package
from package.views import (
    ajax_package_list,
    usage,
    post_data,
    edit_documentation,
)

from .views import (
    CategoryDetailView,
    PackageDetailView,
    PackageListView,
    PackageCreateView,
    PackageUpdateView,
)


urlpatterns = patterns('',
    url(r'^$', PackageListView.as_view(), name='packages',),
    url(r'^p/(?P<slug>[-\w]+)/$', PackageDetailView.as_view(), name='package',),
    url(r'^c/(?P<slug>[-\w]+)/$', CategoryDetailView.as_view(), name='category'),
    url(r'^latest/$', view=ArchiveIndexView.as_view(queryset=Package.objects.filter().select_related(), paginate_by=50, date_field='created'), name='latest_packages',),
    url(r'^add/$', PackageCreateView.as_view(), name='add_package',),
    url(r'^(?P<slug>[-\w]+)/edit/$', PackageUpdateView.as_view(), name='edit_package',),
    url(r'^(?P<slug>[-\w]+)/post-data/$', view=post_data, name='post_package_data',),
    url(r'^usage/(?P<slug>[-\w]+)/(?P<action>add|remove)/$', view=usage, name='usage',),
    url(r'^(?P<slug>[-\w]+)/document/$', view=edit_documentation, name='edit_documentation',),
    url(r'^ajax_package_list/$', view=ajax_package_list, name='ajax_package_list',),
)

django/website/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

from homepage.views import HomePageView
from profiles.views import ProfileRedirectView

admin.autodiscover()
handler404 = 'homepage.views.error_404_view'
handler500 = 'homepage.views.error_500_view'

urlpatterns = patterns('',
    # Examples:
    # url(r'^myapp/', include('myapp.urls')),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^datasets/', include('package.urls')),
    url(r'^grids/', include('grid.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^publishers/', include('publisher.urls')),
    url(r'^datamap/', include('datamap.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/$', ProfileRedirectView.as_view()),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='pages/faq.html'), name='about'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^faq/$', TemplateView.as_view(template_name='pages/faq.html'), name='faq'),
    url(r'^syndication/$', TemplateView.as_view(template_name='pages/syndication.html'), name='syndication'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),

    # This requires that static files are served from the 'static' folder.
    # The apache conf is set up to do this for you, but you will need to do it
    # on dev
    (r'/favicon.ico', 'django.views.generic.base.RedirectView',
        {'url':  '{0}images/favicon.ico'.format(settings.STATIC_URL)}),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

django/website/grid/models.py
from django.core.cache import cache
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.models import BaseModel
from grid.utils import make_template_fragment_key
from package.models import Package


class Grid(BaseModel):
    """Grid object, inherits form :class:`package.models.BaseModel`. Attributes:

    * :attr:`~grid.models.Grid.title` - grid title
    * :attr:`~grid.models.Grid.slug` - grid slug for SEO
    * :attr:`~grid.models.Grid.description` - description of the grid
      with line breaks and urlized links
    * :attr:`~grid.models.Grid.is_locked` - boolean field accessible
      to moderators
    * :attr:`~grid.models.Grid.packages` - many-to-many relation
      with :class:~`grid.models.GridPackage` objects
    """

    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(_('Slug'), help_text="Slugs will be lowercased", unique=True)
    description = models.TextField(_('Description'), blank=True, help_text="Lines are broken and urls are urlized")
    is_locked = models.BooleanField(_('Is Locked'), default=False, help_text="Moderators can lock grid access")
    packages = models.ManyToManyField(Package, through="GridPackage", related_name='grids')
    header = models.BooleanField(_("Header tab?"), default=True, help_text="If checked then displayed on homepage header")

    def elements(self):
        elements = []
        for feature in self.feature_set.all():
            for element in feature.element_set.all():
                elements.append(element)
        return elements

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def grid_packages(self):
        """ Gets all the packages and orders them for views and other things
         """
        gp = self.gridpackage_set.select_related('gridpackage', 'package__repo', 'package__category')
        grid_packages = gp.annotate(usage_count=models.Count('package__usage')).order_by('-usage_count', 'package')
        return grid_packages

        """
        key, grid_packages = cache_fetcher(cachekeys.grid_grid_packages, self)
        if grid_packages is not None:
            return grid_packages
        gp = self.gridpackage_set.select_related('gridpackage', 'package__repo', 'package__category')
        grid_packages = gp.annotate(usage_count=models.Count('package__usage')).order_by('-usage_count', 'package')
        cache.set(key, grid_packages, settings.CACHE_TIMEOUT)
        return grid_packages
        """

    def save(self, *args, **kwargs):
        self.grid_packages  # fire the cache
        self.clear_detail_template_cache()  # Delete the template fragment cache
        super(Grid, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("grid", [self.slug])

    def clear_detail_template_cache(self):
        key = make_template_fragment_key("detail_template_cache", [self.pk, ])
        cache.delete(key)

    class Meta:
        ordering = ['title']


class GridPackage(BaseModel):
    """Grid package.
    This model describes packages listed on one side of the grids
    and
    explicitly defines the many-to-many relationship between grids
    and the packages
    (i.e - allows any given package to be assigned to several grids at once).

    Attributes:

    * :attr:`grid` - the :class:`~grid.models.Grid` to which the package is assigned
    * :attr:`package` - the :class:`~grid.models.Package`
    """

    grid = models.ForeignKey(Grid)
    package = models.ForeignKey(Package)

    class Meta:
        verbose_name = 'Grid Package'
        verbose_name_plural = 'Grid Packages'

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(GridPackage, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s' % (self.grid.slug, self.package.slug)


class Feature(BaseModel):
    """ These are the features measured against a grid.
    ``Feature`` has the following attributes:

    * :attr:`grid` - the grid to which the feature is assigned
    * :attr:`title` - name of the feature (100 chars is max)
    * :attr:`description` - plain-text description
    """

    grid = models.ForeignKey(Grid)
    title = models.CharField(_('Title'), max_length=100)
    description = models.TextField(_('Description'), blank=True)

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(Feature, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s' % (self.grid.slug, self.title)

help_text = """
Linebreaks are turned into 'br' tags<br />
Urls are turned into links<br />
You can use just 'check', 'yes', 'good' to place a checkmark icon.<br />
You can use 'bad', 'negative', 'evil', 'sucks', 'no' to place a negative icon.<br />
Plus just '+' or '-' signs can be used but cap at 3 multiples to protect layout<br/>

"""


class Element(BaseModel):
    """ The individual cells on the grid.
    The ``Element`` grid attributes are:

    * :attr:`grid_package` - foreign key to :class:`~grid.models.GridPackage`
    * :attr:`feature` - foreign key to :class:`~grid.models.Feature`
    * :attr:`text` - the actual contents of the grid cell
    """

    grid_package = models.ForeignKey(GridPackage)
    feature = models.ForeignKey(Feature)
    text = models.TextField(_('text'), blank=True, help_text=help_text)

    class Meta:

        ordering = ["-id"]

    def save(self, *args, **kwargs):
        self.feature.save()  # fire grid_packages cache
        super(Element, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s : %s' % (self.grid_package.grid.slug, self.grid_package.package.slug, self.feature.title)

django/website/package/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from distutils.version import LooseVersion as versioner

from core.models import BaseModel
from publisher.models import Publisher

from package.utils import normalize_license

from international.models import languages


class Category(BaseModel):
    title = models.CharField(_('Title'), max_length='50')
    slug = models.SlugField(_('slug'))
    description = models.TextField(_('description'), blank=True)
    title_plural = models.CharField(_('Title Plural'),
                                    max_length='50',
                                    blank=True)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def package_count(self):
        return self.packages.count()


class Format(BaseModel):
    title = models.CharField(_('Title'), max_length='100')
    slug = models.SlugField(
        _('Slug'),
        help_text='Enter a valid "slug" consisting of letters, numbers, \
            underscores or hyphens. Values will be converted to lowercase.',
        unique=True)
    description = models.TextField(_('Description'), blank=True)

    def __unicode__(self):
        return u'%s' % self.title


class Package(BaseModel):
    """
    A package is a dataset in our revamp.
    """
    title = models.CharField(
        _('Title'),
        max_length='100',
        help_text='Translatable. Please provide in English here, and add translation at bottom of page'  # nopep8
    )
    slug = models.SlugField(
        _('Slug'),
        help_text='Enter a valid "slug" consisting of letters, numbers, \
            underscores or hyphens. Values will be converted to lowercase.',
        unique=True)
    category = models.ForeignKey(Category, related_name='packages')
    description = models.TextField(
        _('Description'),
        blank=True,
        help_text='Translatable. Please provide in English here, and add translation at bottom of page'  # nopep8
    )
    url = models.URLField(
        _('Link'),
        help_text='Enter the URL where the dataset is hosted.',
        blank=True)
    usage = models.ManyToManyField(User, blank=True)
    publisher = models.ForeignKey(Publisher,
                                  blank=True,
                                  null=True,
                                  related_name='datasets',
                                  on_delete=models.SET_NULL)
    created_by = models.ForeignKey(User,
                                   blank=True,
                                   null=True,
                                   related_name='creator',
                                   on_delete=models.SET_NULL)
    last_modified_by = models.ForeignKey(User,
                                         blank=True,
                                         null=True,
                                         related_name='modifier',
                                         on_delete=models.SET_NULL)
    documentation = models.NullBooleanField(
        _('Documentation?'),
        help_text='Is documentation available?',
        null=True,
    )
    documentation_url = models.URLField(_('Documentation URL'),
                                        blank=True,
                                        null=True,
                                        default='')
    ########## Dataset qualities
    machine_readable = models.BooleanField(
        _('Machine Readable'),
        help_text='Is the dataset available in a machine readable, format - json, csv, xml, API',  # nopep8
        blank=True)
    formats = models.ManyToManyField(Format)
    nesting_depth = models.IntegerField(
        _('Nesting Depth'),
        help_text='How deep is the nesting of the data?',
        choices=((0, 'Flat'),
                 (1, 'Low nesting'),
                 (2, 'High nesting')),
        blank=True,
        null=True)
    nesting = models.TextField(
        _('Nesting Description'),
        help_text='Is the data flat or nested, or available as both? Other nesting notes.',  # nopep8
        blank=True)

    class Meta:
        verbose_name = 'dataset'
        verbose_name_plural = 'datasets'

    def get_usage_count(self):
        return self.usage.count()

    @property
    def usage_count(self):
        return self.usage.count()

    def __unicode__(self):
        return u'%s' % self.title

    def grid_clear_detail_template_cache(self):
        grids = (x.grid for x in self.gridpackage_set.all())
        for grid in grids:
            grid.clear_detail_template_cache()

    @models.permalink
    def get_absolute_url(self):
        return ('package', [self.slug])


class TranslatedPackage(BaseModel):
    package = models.ForeignKey(Package, related_name='translations')
    language = models.CharField(_('Language'),
                                max_length=10,
                                choices=languages,
                                default='en_US')
    title = models.CharField(_('Title'), max_length='100')
    description = models.TextField(_('Description'), blank=True)

    def language_name(self):
        dc = dict(languages)
        return dc.get(self.language)


class VersionManager(models.Manager):
    def by_version(self, *args, **kwargs):
        qs = self.get_query_set().filter(*args, **kwargs)
        return sorted(qs, key=lambda v: versioner(v.number))

    def by_version_not_hidden(self, *args, **kwargs):
        qs = self.get_query_set().filter(*args, **kwargs)
        qs = qs.filter(hidden=False)
        qs = sorted(qs, key=lambda v: versioner(v.number))
        qs.reverse()
        return qs


class Version(BaseModel):
    package = models.ForeignKey(Package, blank=True, null=True)
    number = models.CharField(_('Version'),
                              max_length='100',
                              default='',
                              blank='')
    license = models.CharField(_('license'), max_length='100')
    hidden = models.BooleanField(_('hidden'), default=False)
    upload_time = models.DateTimeField(_('upload_time'),
                                       help_text=_('When this was uploaded?'),
                                       blank=True,
                                       null=True)
    objects = VersionManager()

    class Meta:
        get_latest_by = 'upload_time'
        ordering = ['-upload_time']

    @property
    def pretty_license(self):
        return self.license.replace('License', '').replace('license', '')

    @property
    def pretty_status(self):
        return self.get_development_status_display().split(' ')[-1]

    def save(self, *args, **kwargs):
        self.license = normalize_license(self.license)
        super(Version, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s: %s' % (self.package, self.number)

django/website/package/forms.py
from floppyforms import ModelForm, ModelMultipleChoiceField

from core.widgets import BetterSelectMultiple

from package.models import Category, Package, Format


def package_help_text():
    help_text = ""
    for category in Category.objects.all():
        help_text += """
        <li><strong>{title}</strong> -  {description}</li>""".format(
            title=category.title, description=category.description)
    help_text = "<ul>{0}</ul>".format(help_text)
    return help_text


class PackageForm(ModelForm):
    formats = ModelMultipleChoiceField(
        required=False,
        queryset=Format.objects.all(),
        widget=BetterSelectMultiple(attrs={
            'data-add': '&darr; Add',
            'data-remove': '&uarr; Remove',
            'size': 3,
            'style': 'width: 30%',
        }),
    )

    def __init__(self, *args, **kwargs):
            super(PackageForm, self).__init__(*args, **kwargs)
            self.fields['category'].help_text = package_help_text()
            self.fields['url'].required = True

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

    class Meta:
        model = Package
        exclude = ['usage', 'created_by', 'last_modified_by']


class DocumentationForm(ModelForm):

    class Meta:
        model = Package
        fields = ["documentation_url", ]

django/website/package/templates/package/ajax_package_list.html
{% load i18n %}
<div id="target">
    <h2>{% if packages|length %}{% trans "Datasets" %}{% else %}{% trans "No datasets found" %}{% endif %}</h2>
    {% if packages|length %}
        <p class="editable-cell">{% trans "Click a package to add it to the grid." %}</p>      
    {% endif %}
    {% for package in packages %}
        {% include "package/includes/_package_no_link.html" %}
    {% endfor %}
    <script type="text/javascript">
       
        {% for package in packages %}
            {% if package.slug not in packages_already_added_list %}
                $('#package-{{ package.id }}').mouseover(function() {
                    $('#package-{{ package.id }}').addClass("clickable");
                });
                $('#package-{{ package.id }}').mouseout(function() {
                    $('#package-{{ package.id }}').removeClass("clickable");
                });
                $('#package-{{ package.id }}').click(function() {
                
                    $('#package-field').attr("value", {{ package.id }});
                    $("form#grid-package-form").submit();
                });
            {% endif %}
        {% endfor %}

    </script>    
</div>

django/website/package/templates/package/category.html
{% extends "base.html" %}

{% load url from future %}
{% load cache %}
{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">{% trans "home" %}</a></li>
            <li><a href="{% url 'packages' %}">{% trans "datasets" %}</a></li>
            <li class="active">category - {{ category.title|lower }} ({{ category.package_count }})</li>
        </ol>
      <p>{{ category.description }}</p>
      <p>
        {% if user.profile.can_add_package %}
          <a class="btn btn-default" href="{% url 'add_package' %}">{% trans "add package" %} »</a>
        {% endif %}
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
        {% include 'package/package_table.html' %}
   </div>
  </div>

{% endblock %}

django/website/package/templates/package/documentation_form.html
{% extends "base.html" %}

{% load url from future %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "package documentation form" %}{% endblock %}

{% block body %}

    <h2><a href="{% url 'home' %}">{% trans "home" %}</a> / <a href="{% url 'packages' %}">{% trans "packages" %}</a> / {{ action|title }} {% trans "package" %}</h2>

    <p id="package-form-message"></p>    
    <form action="{{ request.path }}" method="post" id="package-form">
        {{ form.errors }}
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
        </fieldset>
        
        <input class="btn btn-default" type="submit" name="add" value="{{ action }} {% trans "Submit" %}">
    </form>

{% endblock %}

{% block extra_body %}
{% if not package.documentation_url.strip %}
<script type="text/javascript">
    $(function() {
        var url = "https://readthedocs.org/api/v1/build/{{ package.slug }}/?format=jsonp";
        $.ajax({
          url: url,
          dataType: 'jsonp',
          success:function(data){
              if (data.objects.length > 0){
                  var href = "https://readthedocs.org/projects/{{ package.slug }}";
                  $("#id_documentation_url").val(href);
              };
          }
        });
    });
</script>
{% endif %}

{% endblock %}

django/website/package/templates/package/package.html
{% extends "base.html" %}

{% load url from future %}
{% load i18n %}
{% load package_tags %}

{% block head_title %}{{ package.title }}{% endblock %}

{% block extra_head %}
  <meta name="description" content="{{ package.description }}" />
  <meta name="keywords" content="{{ package.grid_set.all|join:',' }}" />
  {{ block.super }}
{% endblock %}

{% block body %}
<div class="row">
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans "home" %}</a></li> 
        <li><a href="{% url 'packages' %}">{% trans "datasets" %}</a></li> 
        <li class="active">{{ package.title }} <a href="{% url 'edit_package' package.slug %}"><span class="glyphicon glyphicon-pencil"></span></a></li>
    </ol>
  
  <div class="col-md-6">

    <!-- start Description panel -->
    <div class="panel panel-default">
        <dl class="dl-horizontal">
            <dt>{% trans "Publisher" %}</dt>
            <dd>{% if package.publisher %}<a href="{% url 'publisher' package.publisher.slug %}">{{ package.publisher }}</a> ({{ package.publisher.country_name }}){% endif %}</dd>
        </dl>
        <div class="lang-tabs">
            <ul class="nav nav-tabs pull-right">
                <li><a href="#tabs-en_US" title="English">EN</a></li>
                {% for translation in package.translations.all %}
                <li><a href="#tabs-{{ translation.language }}" title="{{ translation.language_name }}">{{ translation.language|truncatecharsbrute:2|upper }}</a></li>
                {% endfor %}
            </ul>
            <div class="clearfix"></div>
            <div id="tabs-en_US">
            <dl class="dl-horizontal">
                <dt>{% trans "Title" %}</dt>
                <dd class="title">{{ package.title }}</dd>
                <dt>{% trans "Description" %}</dt>
                <dd class="description">{{ package.description|urlize|linebreaksbr }}</dd>
            </dl>
            </div>
            {% for translation in package.translations.all %}
            <div id="tabs-{{ translation.language }}">
            <dl class="dl-horizontal">
                <dt>{% trans "Title" %}</dt>
                <dd class="title">{{ translation.title }}</dd>
                <dt>{% trans "Description" %}</dt>
                <dd class="description">{{ translation.description|urlize|linebreaksbr }}</dd>
            </dl>
            </div>
            {% endfor %}
        </div>
        <dl class="dl-horizontal">
            <dt>{% trans "Category" %}</dt>
            <dd> <a href="{% url 'category' package.category.slug %}">{{ package.category }}</a> </dd>

            <dt>{% trans "# Using This" %}</dt>
            <dd> {{ package.usage.count }} &nbsp; {% with package as package %} {% usage_button %} {% endwith %} </dd>


            <dt>{% trans "Link" %}</dt>
            <dd>{{ package.url|urlizetrunc:40 }}</dd>

            <dt>{% trans "Documentation" %}</dt>
            <dd>{{ package.documentation|yesno|capfirst }} 
                {% if package.documentation %}
                    - {{ package.documentation_url|urlizetrunc:40}}
                {% endif %}
            </dd>

            <dt>{% trans "Machine Readable?" %}</dt>
            <dd>{{ package.machine_readable|yesno|capfirst }}</dd>

            <dt>{% trans "Formats" %}</dt>
            <dd>{% for format in package.formats.all %}{{ format.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</dd>

            <dt>{% trans "Nesting depth" %}</dt>
            <dd>{{ package.get_nesting_depth_display }}</dd>

            <dt>{% trans "Nesting description" %}</dt>
            <dd>{{ package.nesting }}</dd>
        </dl>
    </div>
    <!-- end Description panel -->

  </div> <!-- end six column section -->


  <div class="col-md-6">

    <!-- start Grids panel -->
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left">{% trans "Comparison Grids" %}</h3>
        <div class="pull-right">
          {% if user.is_authenticated and user.profile.can_add_grid %}
            <a id="find-a-grid" href="#"><span class="glyphicon glyphicon-plus"></span></a>
            {% include "package/includes/_attach_grid.html" %}
          {% endif %}
        </div>
      </div>
      <div class="panel-body">
        <ul>
        {% for grid in package.grids.all %}
        <li><a href="{% url 'grid' grid.slug %}" title="{{ grid.description }}">{{ grid }}</a></li>
        {% endfor %}
        </ul>
      </div>
    </div>
    <!-- end Grids panel -->
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left">{% trans "Datamaps" %}</h3>
        <div class="pull-right">
          {% if user.is_authenticated and user.profile.can_add_datamap %}
          <a title="add datamap" href="{% url 'datamap_add' %}?dataset={{ package.pk }}"><span class="glyphicon glyphicon-plus"></span></a>
          {% endif %}
        </div>
      </div>
      <div class="panel-body">
        <ul>
        {% for datamap in package.datamaps.all %}
            <li><a href="{% url 'datamap' datamap.id %}" title="{{ datamap }}">{{ datamap.format }}</a></li>
        {% endfor %}
        </ul>
      </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/underscore.js" type="text/javascript"></script>
  <script src="{{ STATIC_URL }}js/gh3.js" type="text/javascript"></script>
  <script src="{{ STATIC_URL }}js/jquery.tabs.min.js" type="text/javascript"></script>
{% endblock %}

{% block extra_body %}

<script type="text/javascript">
    $(function() {

        $('#find-a-grid').click(function(e) {
            e.preventDefault();
            $('#find-a-grid').hide();
            $('#find-a-grid-form').show();
            $('#find-a-grid-input').focus();

            $('#find-a-grid-input').keyup(function() {
                var search_text = $('input#find-a-grid-input').val();
                var search_text = '{% url 'ajax_grid_list' %}?q=' + search_text + '&package_id={{ package.id }}';
                console.log(search_text);
                $.get(search_text, function(data) {
                  $('#target').html(data).show("slow");
                });
            });

            $("#find-a-grid-form").keypress(function(e) {
                  if (e.which == 13) {
                    return false;
                  };
            });

        });

        $('.lang-tabs').tabs({event: "mouseover"});
    });
</script>
{% endblock %}

django/website/package/templates/package/package_archive.html
{% extends "base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% trans "Packages" %}{% endblock %}

{% block body %}
<div class="row">
  <div class="col-xs-12">
    <h2>{% trans "Latest 50 packages added" %}</h2>
    {% if profile.can_add_package %}
    <p><a class="btn  btn-default" href="{% url 'add_package' %}">{% trans "Add a new package!" %}</a></p>
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="list-group">
        {% for package in latest %}
            {% include "package/includes/_package.html"%}
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

django/website/package/templates/package/package_form.html
{% extends "base.html" %}

{% load url from future %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{{ action|title }} {% trans "package" %}{% endblock %}

{% block body %}
<div class="row">
    <div class="col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">{% trans "home" %}</a></li>
            <li><a href="{% url 'packages' %}">{% trans "datasets" %}</a></li>
            <li class="active">{% trans "edit dataset" %}</li>
        </ol>

        <form action="{{ request.path }}" method="post" id="package-form"> {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <fieldset>
                <h4>Add Translations</h4>
                <p>If you want to add more, save the dataset and then edit and you will be able to add more.</p>
                {% for form in inlines %}
                    {{ form|crispy }}
                {% endfor %}
            </fieldset>
            <input class="btn btn-default" type="submit" name="add" value="{% trans "save dataset" %}">
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/multi_select.js" type="text/javascript"></script>
{% endblock %}

django/website/package/templates/package/package_list.html
{% extends "base.html" %}

{% load url from future %}
{% load i18n %}

{% block head_title %}{% trans "django reusable apps, sites and tools directory" %}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-xs-12">
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans "home" %}</a></li>
        <li class="active">{% trans 'datasets' %}</li>
    </ol>
    <p>
    {% if user.profile.can_add_package %}
        <a class="btn btn-default" href="{% url 'add_package' %}">{% trans "add dataset" %} »</a>
    {% endif %}
    </p>
    {% regroup packages by category as categories %}
    {% for category in categories %}
    <h3><a href="{% url 'category' category.grouper.slug %}">{{ category.grouper.title }}</a> ({{ category.grouper.package_count }})</h3>
    <p>{{ category.grouper.description }}</p>
    {% with category.list as packages %}
        {% include 'package/package_table.html' %}
    {% endwith %}
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {
        $('input#id_q_p').click(function() {
            $("input#id_q_p").val('');
        });
    });
</script>
{% endblock %}