django/website/grid/urls.py
from django.conf.urls import patterns, url

from grid.views import (
    add_feature,
    add_grid,
    add_grid_package,
    add_new_grid_package,
    ajax_grid_list,
    delete_feature,
    delete_grid_package,
    edit_element,
    edit_grid,
    edit_feature,
    grids,
    grid_detail_landscape,
)

from .views import (
    GridDetailView,
)

urlpatterns = patterns("",
    url(r'^add/$', view=add_grid, name='add_grid',),
    url(r'^(?P<slug>[-\w]+)/edit/$', view=edit_grid, name='edit_grid',),
    url(r'^element/(?P<feature_id>\d+)/(?P<package_id>\d+)/$', view=edit_element, name='edit_element',),
    url(r'^feature/add/(?P<grid_slug>[a-z0-9\-\_]+)/$', view=add_feature, name='add_feature',),
    url(r'^feature/(?P<id>\d+)/$', view=edit_feature, name='edit_feature',),
    url(r'^feature/(?P<id>\d+)/delete/$', view=delete_feature, name='delete_feature',),
    url(r'^package/(?P<id>\d+)/delete/$', view=delete_grid_package, name='delete_grid_package',),
    url(r'^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/$', view=add_grid_package, name='add_grid_package',),
    url(r'^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/new$', view=add_new_grid_package, name='add_new_grid_package',),
    url(r'^ajax_grid_list/$', view=ajax_grid_list, name='ajax_grid_list',),
    url(r'^$', view=grids, name='grids',),
    url(r'^g/(?P<slug>[-\w]+)/$', GridDetailView.as_view(), name='grid',),
    url(r'^g/(?P<slug>[-\w]+)/landscape/$', view=grid_detail_landscape, name='grid_landscape',),
)

django/website/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

from homepage.views import HomePageView
from profiles.views import ProfileRedirectView

admin.autodiscover()
handler404 = 'homepage.views.error_404_view'
handler500 = 'homepage.views.error_500_view'

urlpatterns = patterns('',
    # Examples:
    # url(r'^myapp/', include('myapp.urls')),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^datasets/', include('package.urls')),
    url(r'^grids/', include('grid.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^publishers/', include('publisher.urls')),
    url(r'^datamap/', include('datamap.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/$', ProfileRedirectView.as_view()),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='pages/faq.html'), name='about'),
    url(r'^terms/$', TemplateView.as_view(template_name='pages/terms.html'), name='terms'),
    url(r'^faq/$', TemplateView.as_view(template_name='pages/faq.html'), name='faq'),
    url(r'^syndication/$', TemplateView.as_view(template_name='pages/syndication.html'), name='syndication'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),

    # This requires that static files are served from the 'static' folder.
    # The apache conf is set up to do this for you, but you will need to do it
    # on dev
    (r'/favicon.ico', 'django.views.generic.base.RedirectView',
        {'url':  '{0}images/favicon.ico'.format(settings.STATIC_URL)}),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

django/website/grid/models.py
from django.core.cache import cache
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.models import BaseModel
from grid.utils import make_template_fragment_key
from package.models import Package


class Grid(BaseModel):
    """Grid object, inherits form :class:`package.models.BaseModel`. Attributes:

    * :attr:`~grid.models.Grid.title` - grid title
    * :attr:`~grid.models.Grid.slug` - grid slug for SEO
    * :attr:`~grid.models.Grid.description` - description of the grid
      with line breaks and urlized links
    * :attr:`~grid.models.Grid.is_locked` - boolean field accessible
      to moderators
    * :attr:`~grid.models.Grid.packages` - many-to-many relation
      with :class:~`grid.models.GridPackage` objects
    """

    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(_('Slug'), help_text="Slugs will be lowercased", unique=True)
    description = models.TextField(_('Description'), blank=True, help_text="Lines are broken and urls are urlized")
    is_locked = models.BooleanField(_('Is Locked'), default=False, help_text="Moderators can lock grid access")
    packages = models.ManyToManyField(Package, through="GridPackage", related_name='grids')
    header = models.BooleanField(_("Header tab?"), default=True, help_text="If checked then displayed on homepage header")

    def elements(self):
        elements = []
        for feature in self.feature_set.all():
            for element in feature.element_set.all():
                elements.append(element)
        return elements

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def grid_packages(self):
        """ Gets all the packages and orders them for views and other things
         """
        gp = self.gridpackage_set.select_related('gridpackage', 'package__repo', 'package__category')
        grid_packages = gp.annotate(usage_count=models.Count('package__usage')).order_by('-usage_count', 'package')
        return grid_packages

        """
        key, grid_packages = cache_fetcher(cachekeys.grid_grid_packages, self)
        if grid_packages is not None:
            return grid_packages
        gp = self.gridpackage_set.select_related('gridpackage', 'package__repo', 'package__category')
        grid_packages = gp.annotate(usage_count=models.Count('package__usage')).order_by('-usage_count', 'package')
        cache.set(key, grid_packages, settings.CACHE_TIMEOUT)
        return grid_packages
        """

    def save(self, *args, **kwargs):
        self.grid_packages  # fire the cache
        self.clear_detail_template_cache()  # Delete the template fragment cache
        super(Grid, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("grid", [self.slug])

    def clear_detail_template_cache(self):
        key = make_template_fragment_key("detail_template_cache", [self.pk, ])
        cache.delete(key)

    class Meta:
        ordering = ['title']


class GridPackage(BaseModel):
    """Grid package.
    This model describes packages listed on one side of the grids
    and
    explicitly defines the many-to-many relationship between grids
    and the packages
    (i.e - allows any given package to be assigned to several grids at once).

    Attributes:

    * :attr:`grid` - the :class:`~grid.models.Grid` to which the package is assigned
    * :attr:`package` - the :class:`~grid.models.Package`
    """

    grid = models.ForeignKey(Grid)
    package = models.ForeignKey(Package)

    class Meta:
        verbose_name = 'Grid Package'
        verbose_name_plural = 'Grid Packages'

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(GridPackage, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s' % (self.grid.slug, self.package.slug)


class Feature(BaseModel):
    """ These are the features measured against a grid.
    ``Feature`` has the following attributes:

    * :attr:`grid` - the grid to which the feature is assigned
    * :attr:`title` - name of the feature (100 chars is max)
    * :attr:`description` - plain-text description
    """

    grid = models.ForeignKey(Grid)
    title = models.CharField(_('Title'), max_length=100)
    description = models.TextField(_('Description'), blank=True)

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(Feature, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s' % (self.grid.slug, self.title)

help_text = """
Linebreaks are turned into 'br' tags<br />
Urls are turned into links<br />
You can use just 'check', 'yes', 'good' to place a checkmark icon.<br />
You can use 'bad', 'negative', 'evil', 'sucks', 'no' to place a negative icon.<br />
Plus just '+' or '-' signs can be used but cap at 3 multiples to protect layout<br/>

"""


class Element(BaseModel):
    """ The individual cells on the grid.
    The ``Element`` grid attributes are:

    * :attr:`grid_package` - foreign key to :class:`~grid.models.GridPackage`
    * :attr:`feature` - foreign key to :class:`~grid.models.Feature`
    * :attr:`text` - the actual contents of the grid cell
    """

    grid_package = models.ForeignKey(GridPackage)
    feature = models.ForeignKey(Feature)
    text = models.TextField(_('text'), blank=True, help_text=help_text)

    class Meta:

        ordering = ["-id"]

    def save(self, *args, **kwargs):
        self.feature.save()  # fire grid_packages cache
        super(Element, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s : %s : %s' % (self.grid_package.grid.slug, self.grid_package.package.slug, self.feature.title)

django/website/package/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from distutils.version import LooseVersion as versioner

from core.models import BaseModel
from publisher.models import Publisher

from package.utils import normalize_license

from international.models import languages


class Category(BaseModel):
    title = models.CharField(_('Title'), max_length='50')
    slug = models.SlugField(_('slug'))
    description = models.TextField(_('description'), blank=True)
    title_plural = models.CharField(_('Title Plural'),
                                    max_length='50',
                                    blank=True)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return u'%s' % self.title

    @property
    def package_count(self):
        return self.packages.count()


class Format(BaseModel):
    title = models.CharField(_('Title'), max_length='100')
    slug = models.SlugField(
        _('Slug'),
        help_text='Enter a valid "slug" consisting of letters, numbers, \
            underscores or hyphens. Values will be converted to lowercase.',
        unique=True)
    description = models.TextField(_('Description'), blank=True)

    def __unicode__(self):
        return u'%s' % self.title


class Package(BaseModel):
    """
    A package is a dataset in our revamp.
    """
    title = models.CharField(
        _('Title'),
        max_length='100',
        help_text='Translatable. Please provide in English here, and add translation at bottom of page'  # nopep8
    )
    slug = models.SlugField(
        _('Slug'),
        help_text='Enter a valid "slug" consisting of letters, numbers, \
            underscores or hyphens. Values will be converted to lowercase.',
        unique=True)
    category = models.ForeignKey(Category, related_name='packages')
    description = models.TextField(
        _('Description'),
        blank=True,
        help_text='Translatable. Please provide in English here, and add translation at bottom of page'  # nopep8
    )
    url = models.URLField(
        _('Link'),
        help_text='Enter the URL where the dataset is hosted.',
        blank=True)
    usage = models.ManyToManyField(User, blank=True)
    publisher = models.ForeignKey(Publisher,
                                  blank=True,
                                  null=True,
                                  related_name='datasets',
                                  on_delete=models.SET_NULL)
    created_by = models.ForeignKey(User,
                                   blank=True,
                                   null=True,
                                   related_name='creator',
                                   on_delete=models.SET_NULL)
    last_modified_by = models.ForeignKey(User,
                                         blank=True,
                                         null=True,
                                         related_name='modifier',
                                         on_delete=models.SET_NULL)
    documentation = models.NullBooleanField(
        _('Documentation?'),
        help_text='Is documentation available?',
        null=True,
    )
    documentation_url = models.URLField(_('Documentation URL'),
                                        blank=True,
                                        null=True,
                                        default='')
    ########## Dataset qualities
    machine_readable = models.BooleanField(
        _('Machine Readable'),
        help_text='Is the dataset available in a machine readable, format - json, csv, xml, API',  # nopep8
        blank=True)
    formats = models.ManyToManyField(Format)
    nesting_depth = models.IntegerField(
        _('Nesting Depth'),
        help_text='How deep is the nesting of the data?',
        choices=((0, 'Flat'),
                 (1, 'Low nesting'),
                 (2, 'High nesting')),
        blank=True,
        null=True)
    nesting = models.TextField(
        _('Nesting Description'),
        help_text='Is the data flat or nested, or available as both? Other nesting notes.',  # nopep8
        blank=True)

    class Meta:
        verbose_name = 'dataset'
        verbose_name_plural = 'datasets'

    def get_usage_count(self):
        return self.usage.count()

    @property
    def usage_count(self):
        return self.usage.count()

    def __unicode__(self):
        return u'%s' % self.title

    def grid_clear_detail_template_cache(self):
        grids = (x.grid for x in self.gridpackage_set.all())
        for grid in grids:
            grid.clear_detail_template_cache()

    @models.permalink
    def get_absolute_url(self):
        return ('package', [self.slug])


class TranslatedPackage(BaseModel):
    package = models.ForeignKey(Package, related_name='translations')
    language = models.CharField(_('Language'),
                                max_length=10,
                                choices=languages,
                                default='en_US')
    title = models.CharField(_('Title'), max_length='100')
    description = models.TextField(_('Description'), blank=True)

    def language_name(self):
        dc = dict(languages)
        return dc.get(self.language)


class VersionManager(models.Manager):
    def by_version(self, *args, **kwargs):
        qs = self.get_query_set().filter(*args, **kwargs)
        return sorted(qs, key=lambda v: versioner(v.number))

    def by_version_not_hidden(self, *args, **kwargs):
        qs = self.get_query_set().filter(*args, **kwargs)
        qs = qs.filter(hidden=False)
        qs = sorted(qs, key=lambda v: versioner(v.number))
        qs.reverse()
        return qs


class Version(BaseModel):
    package = models.ForeignKey(Package, blank=True, null=True)
    number = models.CharField(_('Version'),
                              max_length='100',
                              default='',
                              blank='')
    license = models.CharField(_('license'), max_length='100')
    hidden = models.BooleanField(_('hidden'), default=False)
    upload_time = models.DateTimeField(_('upload_time'),
                                       help_text=_('When this was uploaded?'),
                                       blank=True,
                                       null=True)
    objects = VersionManager()

    class Meta:
        get_latest_by = 'upload_time'
        ordering = ['-upload_time']

    @property
    def pretty_license(self):
        return self.license.replace('License', '').replace('license', '')

    @property
    def pretty_status(self):
        return self.get_development_status_display().split(' ')[-1]

    def save(self, *args, **kwargs):
        self.license = normalize_license(self.license)
        super(Version, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s: %s' % (self.package, self.number)

django/website/grid/forms.py
"""Forms for the :mod:`grid` app
"""

from django.forms import ModelForm

from grid.models import  Element, Feature, Grid, GridPackage


class GridForm(ModelForm):
    """collects data for the new grid - a
    django ``ModelForm`` for :class:`grid.models.Grid`
    """

    def clean_slug(self):
        """returns lower-cased slug"""
        return self.cleaned_data['slug'].lower()

    class Meta:
        model = Grid
        fields = ['title', 'slug', 'description']


class ElementForm(ModelForm):
    """collects data for a new grid element -
    a ``ModelForm`` for :class:`grid.models.Element`
    """

    class Meta:
        model = Element
        fields = ['text', ]


class FeatureForm(ModelForm):
    """collects data for the feature -
    a ``ModelForm`` for :class:`grid.models.Feature`
    """

    class Meta:
        model = Feature
        fields = ['title', 'description', ]


class GridPackageForm(ModelForm):
    """collects data for a new package -
    a ``ModelForm`` for :class:`grid.models.GridPackage`
    """

    class Meta:
        model = GridPackage
        fields = ['package']

django/website/grid/templates/grid/ajax_grid_list.html
{% load i18n %}
{% load url from future %}
<div id="target">
    <h2>{% if grids.count %}{% trans "Grids" %}{% else %}{% trans "No grids found" %}{% endif %}</h2>
    {% if grids.count %}
        <p class="clickable">{% trans "Click a grid to add your grid to it." %}</p>      
    {% endif %}
    {% for grid in grids %}
  

        <dl class="grid-item" id="grid-{{ grid.id }}">

            <dt><strong>{{ grid.title }}</strong></dt>
            <dd class="description">{{ grid.description }}</dd>        
        </dl>
    {% endfor %}
    <script type="text/javascript">
       
        {% for grid in grids %}
            $('#grid-{{ grid.id }}').mouseover(function() {
                $('#grid-{{ grid.id }}').addClass("clickable");
            });
            $('#grid-{{ grid.id }}').mouseout(function() {
                $('#grid-{{ grid.id }}').removeClass("clickable");
            });
            $('#grid-{{ grid.id }}').click(function() {
                $('form#find-a-grid-form').attr('action', "{% url 'add_grid_package' grid.slug %}");
                $("form#find-a-grid-form").submit();
            });
        {% endfor %}

    </script>    
</div>

django/website/grid/templates/grid/base.html
{% extends "base.html" %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/grid.css" />
{% endblock %}


{% block body_class %}grid{% endblock %}

django/website/grid/templates/grid/edit_element.html
{% extends "grid/base.html" %}
{% load url from future %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Edit Element" %}{% endblock %}

{% block body %}

    <h2>{% trans "Edit Element which is related to:" %}</h2>
    
    <p><strong>{% trans "Grid:" %} {{ grid }}</strong></p>
    <p><strong>{% trans "Package:" %} {{ package }}</strong></p>    
    <p><strong>{% trans "Feature:" %} {{ feature.title }}</strong> {{ feature.description}}</p>
    
    
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
            <div class="form_block">        
                <input class="btn btn-success" type="submit" name="edit" value="{% trans "Save" %}">
                &nbsp <a class="btn-sm btn-danger" href="{% url 'grid' grid.slug %}">{% trans "Cancel" %}</a>
            </div>            
            
        </fieldset>
    </form>
    
    <p>
        
    </p>

{% endblock %}

{% block extra_body %}
<script>
    $("#id_text").focus();
</script>
{% endblock %}

django/website/grid/templates/grid/grid_detail.html
{% extends "grid/base.html" %}
{% load url from future %}

{% load i18n %}
{% load cache %}
{% load grid_tags %}
{% load package_tags %}

{% block head_title %}{{ grid.title }}{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <meta name="description" content="{{ grid.description }}" />
    <meta name="keywords" content="{{ grid.package_set.all|join:',' }}" />
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-lg-12">
    <h2>
      {{ grid.title }}
      {% if user.is_authenticated and user.profile.can_edit_grid %}
        <a href="{% url 'edit_grid' grid.slug %}">
          <span class="glyphicon glyphicon-pencil"></span>
        </a>
      {% endif %}
    </h2>
  </div>
</div>
{% cache 2592000 detail_template_cache grid.pk %}
<div class="row">
  <div class="col-lg-{% if features %}3{% else %}6{% endif %}">

    <p>
      {{ grid.description|urlize|linebreaksbr }}
    </p>

    {% if features %}
        {% if request.user.is_authenticated and request.user.profile.can_add_grid_package %}
          <p><a href="{% url 'add_grid_package' grid.slug %}"><span class="glyphicon glyphicon-plus"></span> {% trans "Add dataset to the grid" %}</a></p>
        {% endif %}

        {% if request.user.is_authenticated and request.user.profile.can_add_grid_feature %}
          <p><a href="{% url 'add_feature' grid.slug %}"><span class="glyphicon glyphicon-plus"></span> {% trans "Add new feature to the grid" %}</a></p>
        {% endif %}
    {% endif %}

    {% if request.user.is_authenticated and request.user.profile.can_edit_grid_element and features %}
        <p><span class="glyphicon glyphicon-info-sign"></span> {% trans "Highlighted cells are editable.  Click highlighted cells to change text." %}</p>
    {% endif %}
  </div>
  {% if features %}
      <div class="col-lg-9">
          <h3>{% trans "Features currently being evaluated" %}</h3>
          <table class="table">
            <thead>
              <tr>
                <th>{% trans "Feature" %}</th>
                <th>{% trans "Description" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for feature in features %}
                <tr>
                  <td>{{ feature.title }}
                  {% if request.user.is_authenticated and request.user.profile.can_edit_grid_feature %}
                    &nbsp;<a href="{% url 'edit_feature' feature.pk %}">
                      <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    {% if perms.grid.delete_feature %}
                      &nbsp;<a href="#" id="feature-delete-{{ feature.pk }}">
                        <span class="glyphicon glyphicon-trash"></span>
                      </a>
                    {% endif %}
                  {% endif %}
                  </td>
                  <td>{{ feature.description|wordwrap:80|linebreaksbr }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
  {% else %}
    <div class="col-lg-6">
        {% if request.user.is_authenticated and request.user.profile.can_add_grid_package %}
          <p><a href="{% url 'add_grid_package' grid.slug %}"><span class="glyphicon glyphicon-plus"></span> {% trans "Add package to the grid" %}</a></p>
        {% endif %}

        {% if request.user.is_authenticated and request.user.profile.can_add_grid_feature %}
          <p><a href="{% url 'add_feature' grid.slug %}"><span class="glyphicon glyphicon-plus"></span> {% trans "Add new feature to the grid" %}</a></p>
        {% endif %}
    </div>
  {% endif %}
</div>

<!-- Grid is not inside of a Bootstrap grid row because it needs max width. -->
    {% if grid_packages|length %}
        <table class="table table-condensed">
            <thead>
                {% include "grid/snippets/grid_row_header.html" %}
            </thead>
            <tbody>
                <tr>
                    <td>{% trans "Category" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.category }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Country" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.publisher.country_name }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Publisher" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.publisher.name}}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Machine Readable" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.machine_readable|yesno|capfirst}}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Formats" %}</td>
                    {% for grid_package in grid_packages %}
                    <td>{% for format in grid_package.package.formats.all %}{{ format.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                    {% endfor %}
                </tr>
                {% comment %}
                <tr>
                    <td>{% trans "Nesting depth" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.publisher.nesting_depth }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Nesting description" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.publisher.nesting|truncatewords:25 }}</td>
                    {% endfor %}
                </tr>
                {% endcomment %}
                {% include "grid/snippets/grid_row_header.html" %}
                {% for feature in features %}
                    <tr class="{% cycle 'even' 'odd' %}">
                        <td>{{ feature.title }}</td>
                        {% for grid_package in grid_packages %}
                            {% with elements|hash:feature.pk|hash:grid_package.pk as element %}
                            <td>
                                {% if element %}
                                    {{ element.text|style_element|safe|urlize|linebreaksbr }}
                                {% endif %}
                                {% if request.user.is_authenticated and request.user.profile.can_edit_grid_element %}
                                    <a class="edit" href="{% url 'edit_element' feature.pk grid_package.pk %}"> 
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                {% endif %}
                            </td>
                            {% endwith %}
                        {% endfor %}
                    </tr>
                {% endfor %}
                {% if features %}
                    {% include "grid/snippets/grid_row_header.html" %}
                {% endif %}

                <!-- start Delete package from grid buttons -->
                {% if perms.grid.delete_gridpackage %}
                  <tr>
                    <td>Remove from grid?</td>
                    {% for grid_package in grid_packages %}
                    <td class="grid-delete">
                        &nbsp;<a href="#" id="package-delete-{{ grid_package.pk }}">
                          <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                    {% endfor %}
                  </tr>
                {% endif %}
                <!-- end Delete package from grid buttons -->

            </tbody>

        </table>
    {% else %}
        {% if request.user.is_authenticated and request.user.profile.can_add_grid_package %}
        <p><a href="{% url 'add_grid_package' grid.slug %}"><span class="glyphicon glyphicon-plus"></span>&nbsp;{% trans "Add a package to get a grid view" %}</a></p>
        {% endif %}
    {% endif %}
    {% endcache %}

{% endblock %}

{% block extra_body %}
        <script type="text/javascript">

            $(function() {

                {% if request.user.is_authenticated %}
                
                // Handle element edit redirects
                {% if request.user.profile.can_edit_grid_element %}

                    delete_confirmation = function(e, url) {
                        // The deletes are placed in here so there is just one place needed
                        e.preventDefault();

                        if(confirm('{% trans "Are you sure? This cannot be undone!" %}')) {
                            window.location = url;
                        }
                    };
                {% endif %}
                    // handle feature deletes
                    {% if perms.grid.delete_feature %}
                        $("a[id|='feature-delete']").click(function(e) {
                            var array = $(this).attr("id").split("-");
                            var url = "/grids/feature/" + array[2] + "/delete/";
                            delete_confirmation(e,url);
                        });
                    {% endif %}

                    {% if perms.grid.delete_gridpackage %}
                        // handle package deletes
                        $("a[id|='package-delete']").click(function(e) {
                            var array = $(this).attr("id").split("-");
                            var url = "/grids/package/" + array[2] + "/delete/";
                            delete_confirmation(e,url);
                        });
                    {% endif %}

                 {% endif %}

            });
        </script>
{% endblock %}

django/website/grid/templates/grid/update_feature.html
{% extends "grid/base.html" %}
{% load url from future %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      
      <h2>{% trans "Grid Feature" %}</h2>

      <p>{% trans "Add/edit a feature of the" %} <a href="{% url 'grid' grid.slug %}">{{ grid.title }}</a> {% trans "grid." %}</p>
      
      <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
          {{ form|crispy }}
          <div class="form_block">
            <input class="btn btn-default" type="submit" name="edit" value="Edit">
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script>
    $("#id_title").focus();
</script>
{% endblock %}

django/website/grid/templates/grid/update_grid.html
{% extends "grid/base.html" %}
{% load url from future %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "Edit Grid" %}</h2>
    
      <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
          {{ form|crispy }}
          <div class="form_block">
            <input class="btn btn-default" type="submit" name="add" value="{% trans "Submit »" %}">
          </div>            
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {          
        $('input#id_title').focus();
        
    });    
</script>      
{% endblock %}      
        